### ISSUE TITLE
SwerveIO Is Outdated

### ISSUE THREAD

**Issue by ghost** [Cybersonics/Robot2020#8]
I have noticed that you are using my swerve drive library, SwerveIO on your `master` branch, so I just wanted to inform you that the version you're using is incredibly outdated. Are you using SwerveIO, or are you using the code on the `2910-swerve` branch?

If you are using SwerveIO, the latest version is now `4.0.0`, and is available at a different vendor JSON url (the one you're using, `Team6090.json`, no longer exists). Would you like my help porting your code to the new version? I almost completely re-wrote the API, and I think it is much improved over the version you're using. If you'd like, I can open a pull request against `master` to bring your drivetrain code up to date and save you the time of having to read through the documentation just to get it to compile.

In case you're interested, here's some helpful information:

SwerveIO 4.x is available with the following vendor URL now: https://maven.bancino.net/SwerveIO.json

You can find the user documentation at https://javadoc.bancino.net/SwerveIO/latest/

**Comment by JR33D** [comment]
@jordanbancino Thank you we've noticed this as well and are just starting to look at items for the 20-21 season. We will be moving back to a custom version of swerve code we have inhouse, so we'll no longer be maintaining this code.

**Comment by ghost** [comment]
Alright, cool cool, good luck!
